package com.sinopec.common;

/**
 * Created with IntelliJ IDEA. User: gaochuanjun Date: 13-10-30 Time: 上午9:27 To
 * change this template use File | Settings | File Templates.
 */
public class SQLConstants {
	public static String updateComputeNodeStatusOrcl(String nodeName, String timeString, float oneMinsProcs, float fiveMinsProcs, float fifteenMinsProcs, float userTime, float niceTime, float systemTime, float iowaitTime, float idleTime, String allUserTime, String allNiceTime, String allSystemTime, String allIowaitTime, String allIdleTime, int totalMemory, int usedMemory, int idleMemory, int swapSize, int usedSwap, int idleSwap, int ioTs, int readSpeed, int readKb, int writeSpeed, int writeKb, double inReceivesPs, double inDeliversPs, double outRequestsPs, double inSegsPs, double outSegsPs, double retransSegsPs, double inDatagramsPs, double outDatagramsPs) {
		return "update ComputeNodeStatus set UpdateTime=to_date('" + timeString + "','YYYY-MM-DD HH24:MI:SS'),OneMinsProcs=" + oneMinsProcs + ",FiveMinsProcs=" + fiveMinsProcs + ",FifteenMinsProcs=" + fifteenMinsProcs + ",UserTime=" + userTime + ",NiceTime=" + niceTime + ",SystemTime=" + systemTime + ",IowaitTime=" + iowaitTime + ",IdleTime=" + idleTime + ",AllUserTime='" + allUserTime + "',AllNiceTime='" + allNiceTime + "',AllSystemTime='" + allSystemTime + "',AllIowaitTime='" + allIowaitTime + "',AllIdleTime='" + allIdleTime + "',TotalMemory=" + totalMemory + ",UsedMemory=" + usedMemory + ",IdleMemory=" + idleMemory + ",SwapSize=" + swapSize + ",UsedSwap=" + usedSwap + ",IdleSwap=" + idleSwap + ",IoTs=" + ioTs + ",ReadSpeed=" + readSpeed + ",ReadKB=" + readKb + ",WriteSpeed=" + writeSpeed + ",WriteKB=" + writeKb + ",InReceivesPs=" + inReceivesPs + ",InDeliversPs=" + inDeliversPs + ",OutRequestsPs=" + outRequestsPs + ",InSegsPs=" + inSegsPs + ",OutSegsPs=" + outSegsPs + ",RetransSegsPs=" + retransSegsPs + ",InDatagramsPs=" + inDatagramsPs + ",OutDatagramsPs=" + outDatagramsPs + " where NodeName='" + nodeName + "'";
	}

	public static String updateComputeNodeStatusMySQL(String nodeName, String timeString, float oneMinsProcs, float fiveMinsProcs, float fifteenMinsProcs, float userTime, float niceTime, float systemTime, float iowaitTime, float idleTime, String allUserTime, String allNiceTime, String allSystemTime, String allIowaitTime, String allIdleTime, int totalMemory, int usedMemory, int idleMemory, int swapSize, int usedSwap, int idleSwap, int ioTs, int readSpeed, int readKb, int writeSpeed, int writeKb, double inReceivesPs, double inDeliversPs, double outRequestsPs, double inSegsPs, double outSegsPs, double retransSegsPs, double inDatagramsPs, double outDatagramsPs) {
		return "update ComputeNodeStatus set UpdateTime='" + timeString + "',OneMinsProcs=" + oneMinsProcs + ",FiveMinsProcs=" + fiveMinsProcs + ",FifteenMinsProcs=" + fifteenMinsProcs + ",UserTime=" + userTime + ",NiceTime=" + niceTime + ",SystemTime=" + systemTime + ",IowaitTime=" + iowaitTime + ",IdleTime=" + idleTime + ",AllUserTime='" + allUserTime + "',AllNiceTime='" + allNiceTime + "',AllSystemTime='" + allSystemTime + "',AllIowaitTime='" + allIowaitTime + "',AllIdleTime='" + allIdleTime + "',TotalMemory=" + totalMemory + ",UsedMemory=" + usedMemory + ",IdleMemory=" + idleMemory + ",SwapSize=" + swapSize + ",UsedSwap=" + usedSwap + ",IdleSwap=" + idleSwap + ",IoTs=" + ioTs + ",ReadSpeed=" + readSpeed + ",ReadKB=" + readKb + ",WriteSpeed=" + writeSpeed + ",WriteKB=" + writeKb + ",InReceivesPs=" + inReceivesPs + ",InDeliversPs=" + inDeliversPs + ",OutRequestsPs=" + outRequestsPs + ",InSegsPs=" + inSegsPs + ",OutSegsPs=" + outSegsPs + ",RetransSegsPs=" + retransSegsPs + ",InDatagramsPs=" + inDatagramsPs + ",OutDatagramsPs=" + outDatagramsPs + " where NodeName='" + nodeName + "'";
	}
}
